### ISSUE TITLE
android.os.NetworkOnMainThreadException on loginSilent()

### ISSUE THREAD

**Issue by black-snow** [MSOpenTech/msa-auth-for-android#19]
With the latest Versions (0.8.3) my app crashes with `java.lang.RuntimeException: Unable to start activity ComponentInfo{xxxxxx.MainActivity}: android.os.NetworkOnMainThreadException`.

Stack trace (shortened):

```
E/AndroidRuntime:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
E/AndroidRuntime:     at com.microsoft.services.msa.TokenRequest.execute(TokenRequest.java:104)
E/AndroidRuntime:     at com.microsoft.services.msa.LiveAuthClient.tryRefresh(LiveAuthClient.java:569)
E/AndroidRuntime:     at com.microsoft.services.msa.LiveAuthClient.loginSilent(LiveAuthClient.java:472)
E/AndroidRuntime:     at com.microsoft.services.msa.LiveAuthClient.loginSilent(LiveAuthClient.java:417)
```

Seems like there's suddenly network activity on the main thread when calling `LiveAuthClient.loginSilent()`. Probably slipped in with the latest fix for `loginSilent()`. I'll take a look at the code - just wanted to file an issue first.

**Comment by black-snow** [comment]
Found this in `LiveAuthClient`'s constructor:

``` java
RefreshAccessTokenRequest request = new RefreshAccessTokenRequest(this.httpClient,
    this.clientId,
    this.getRefreshTokenFromPreferences(),
    TextUtils.join(OAuth.SCOPE_DELIMITER, this.baseScopes),
    this.mOAuthConfig);
TokenRequestAsync requestAsync = new TokenRequestAsync(request);
requestAsync.addObserver(new RefreshTokenWriter());
requestAsync.execute();
```

Looks like something similar should be added to `LiveAuthClient.tryRefresh()`, too, which currently looks like this:

``` java
...
RefreshAccessTokenRequest request =
                new RefreshAccessTokenRequest(this.httpClient, this.clientId, refreshToken, scope, mOAuthConfig);

OAuthResponse response;
try {
    response = request.execute();
} catch (LiveAuthException e) {
    return false;
}

SessionRefresher refresher = new SessionRefresher(this.session);
response.accept(refresher);
response.accept(new RefreshTokenWriter());

return refresher.visitedSuccessfulResponse();
```

**Comment by peternied** [comment]
Looks like my fix just introduced that bug, I initialize my MSA client on the background so I missed it, I'll patch this up today.

**Comment by black-snow** [comment]
@peternied Great, looking forward to a 0.8.4
