### ISSUE TITLE
AuthorizationRequest.OAuthDialog.dismiss() is called after activity has finished

### ISSUE THREAD

**Issue by phileo** [MSOpenTech/msa-auth-for-android#26]
This occurs on some phones when pressing "No" on the permissions page and immediately rotating screen.

```
Fatal Exception: java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{297e1da2 V.E..... R......D 0,0-1440,2560} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:412)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:338)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:118)
       at android.app.Dialog.dismissDialog(Dialog.java:522)
       at android.app.Dialog.dismiss(Dialog.java:504)
       at com.microsoft.services.msa.AuthorizationRequest$OAuthDialog$AuthorizationWebViewClient.onPageFinished(AuthorizationRequest.java:115)
       at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:513)
       at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:188)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6872)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by phileo** [comment]
I noticed that my pull request has been merged (thank-you!), and a new version has been published:
https://bintray.com/msopentech/Maven/msa-auth-for-android/0.8.5/view

Does the gradle.properties of this project need to be updated as well?

**Comment by peternied** [comment]
Good catch on the missed version update! this issue should be resolved now.
