### ISSUE TITLE
Crash when rotating screen while using one drive sdk

### ISSUE THREAD

**Issue by modislaszlox2** [MSOpenTech/msa-auth-for-android#34]
Hello,

The issue is that this library is using Dialog to show the webview. Please switch to something else(custom chrome tabs, chrome, Activity).

Issue stack trace:
```java
E/WindowManager: android.view.WindowLeaked: Activity XXX has leaked window DecorView@81a0886[XXX] that was originally added here
                                                                                  at android.view.ViewRootImpl.<init>(ViewRootImpl.java:565)
                                                                                  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                                                  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:97)
                                                                                  at android.app.Dialog.show(Dialog.java:419)
                                                                                  at com.microsoft.services.msa.AuthorizationRequest.execute(AuthorizationRequest.java:350)
                                                                                  at com.microsoft.services.msa.LiveAuthClient.login(LiveAuthClient.java:416)
                                                                                  at com.onedrive.sdk.authentication.MSAAuthenticator$3.run(MSAAuthenticator.java:199)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by modislaszlox2** [comment]
@peternied Please have a look.
